name: Franklin Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm install
    - run: npm run lint
    - run: npm run build --if-present
    - run: |
        sed -i -e '/dist/d' .gitignore
        git config user.name "Github Bot"
        git config user.email "action@github.com"
        git add dist && git commit -m "chore: [$(date +'%Y-%m-%d')] deploy latest build"
        git push
        echo 'dist' >> ./.gitignore
